[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install] 
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT wsgi:application"
