[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
startCommand = "gunicorn --bind 0.0.0.0:$PORT wsgi:application"

[env]
FLASK_ENV = "production"
PYTHONPATH = "."
PIP_NO_CACHE_DIR = "1"
